// Generated by CoffeeScript 1.4.0
(function() {

  require('./server')(function(app) {
    var environment, mongoose;
    mongoose = require('mongoose');
    environment = require('./server/config/environment')();
    mongoose.connect(environment.host, environment.database);
    app.get('/', function(req, res) {
      return res.redirect('/index.html');
    });
    app.listen(3000);
    return console.log("Rodando na porta 3000");
  });

}).call(this);
