// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(callback) {
    var app, express;
    express = require('express');
    app = express();
    require('./server/config')(app, express, __dirname);
    require('./server/router')(app);
    require('./server/controllers/usuarioController')(app);
    return callback(app);
  };

}).call(this);
