// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    host: 'smtp.gmail.com',
    user: 'your-email-address@gmail.com',
    password: 'your-email-password',
    sender: 'Your Name <your-email-address@gmail.com>'
  };

}).call(this);
