// Generated by CoffeeScript 1.4.0
(function() {
  var ambient;

  ambient = "development";

  module.exports = function(pAmbient) {
    var amb;
    amb = {
      test: {
        host: "localhost",
        database: "BasicNodeTest"
      },
      development: {
        host: "localhost",
        database: "BasicNodeDev"
      },
      production: {
        host: "localhost",
        database: "BasicNodeJS"
      }
    };
    if (pAmbient) {
      ambient = pAmbient;
    }
    return amb[ambient];
  };

}).call(this);
