// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(mongoose) {
    var db;
    mongoose.set("debug", true);
    db = mongoose.createConnection("localhost", "dbTeste");
    db.on("connected", function() {
      return console.log("DB conectado a " + db.name + " em " + db.host + ":" + db.port);
    });
    db.on("open", function() {
      return console.log("Conexao com DB aberta.");
    });
    db.on("disconneected", function() {
      return console.log("DB Disconectado.");
    });
    db.on("close", function() {
      return console.log("Conexao com DB fechada.");
    });
    db.on("error", function(err) {
      console.log("Erro na conexao com DB.");
      return assert.ok(err);
    });
    db.on("error", function(err) {
      return console.log(err);
    });
    return db;
  };

}).call(this);
