// Generated by CoffeeScript 1.4.0
(function() {
  var environment;

  environment = "development";

  module.exports = function(pEnvironment) {
    var amb;
    amb = {
      test: {
        host: "localhost",
        database: "BasicNodeTest"
      },
      development: {
        host: "localhost",
        database: "BasicNodeDev"
      },
      production: {
        host: "localhost",
        database: "BasicNodeJS"
      }
    };
    if (pEnvironment) {
      environment = pEnvironment;
    }
    return amb[environment];
  };

}).call(this);
