// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose, sys;

  mongoose = require("mongoose");

  sys = require("sys");

  module.exports = function(app, express, dir) {
    return app.configure(function() {
      app.use(express.methodOverride());
      app.use(express.bodyParser());
      app.use(express.cookieParser("CkKiiE3749S877ss0s75GDDwC&*¨%$"));
      app.use(express.session({
        secret: "C87*889fhgwli&%554$jsHH"
      }));
      return app.use(express["static"]("" + dir + "/public"));
    });
  };

}).call(this);
