// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(app) {
    return app.post("/sessao", function(req, res) {
      console.log(req.sessionID);
      return res.send({
        msg: "ok"
      });
    });
  };

}).call(this);
