// Generated by CoffeeScript 1.4.0
(function() {
  var login, sys;

  sys = require("sys");

  login = require("./login/login");

  module.exports = function(app) {
    app.post("/login", login.login);
    app.post("/logout", function(req, res) {
      return login.logout(req, res);
    });
    app.post("/ver", function(req, res) {
      if (login.requestValidate(req)) {
        return res.send({
          msg: "Sessão válida"
        });
      } else {
        return res.send({
          msg: "Sessão inválida"
        });
      }
    });
    return app.post("/sessao", function(req, res) {
      console.log(req.sessionID);
      return res.send({
        msg: "ok"
      });
    });
  };

}).call(this);
