// Generated by CoffeeScript 1.4.0
(function() {
  var Login, Usuario, app, configDB, db, express, mongoose, msgHelper, request, should;

  mongoose = require("mongoose");

  configDB = require("./../config/environment")("test");

  Usuario = require("./../models/usuarioModel");

  Login = require("./../login/login");

  msgHelper = require("./../helpers/message");

  should = require("should");

  db = void 0;

  mongoose.connection.on("error", function(e) {
    return console.log("Conexão: " + e);
  });

  express = require("express");

  request = require("./support/http");

  app = require("./../../");

  describe("app", function() {
    return describe(".request", function() {
      var user;
      user = {
        nome: "Usuario Login Teste",
        email: "login@com.br",
        senha: "login"
      };
      before(function(done) {
        db = mongoose.connect(configDB.host, configDB.database);
        return Usuario.remove({}, function() {
          var usuarioModel;
          usuarioModel = new Usuario(user);
          return usuarioModel.save(function(e, u) {
            should.not.exist(e);
            should.exist(u);
            return done();
          });
        });
      });
      after(function(done) {
        return db.connection.db.dropDatabase(function() {
          return db.connection.close(function() {
            return done();
          });
        });
      });
      return it("should extend the request prototype", function(done) {
        return request().post('/login').set('Content-Type', 'application/json').write(JSON.stringify({
          email: 'login@com.br',
          senha: 'login'
        })).expect(200, done);
      });
    });
  });

}).call(this);
