// Generated by CoffeeScript 1.4.0
(function() {
  var crypt, sys, usuarioModel;

  sys = require("sys");

  usuarioModel = require("./../usuario/usuarioModel");

  crypt = require("./../seguranca/criptografia");

  module.exports = {
    makeLogin: function(req, res) {
      var email, senha;
      email = req.body.email;
      senha = req.body.senha;
      return usuarioModel.findByEmail(email, (function(usuario) {
        var sessaoUsuario;
        if (!usuario) {
          return res.send(500, {
            err: "Usuário não encontrado."
          });
        } else if (usuario.passValidate(senha)) {
          sessaoUsuario = {
            sID: req.sessionID,
            userID: usuario.id,
            userName: usuario.nome,
            userMail: usuario.email,
            token: crypt.gerarSessionToken(req)
          };
          req.session.user = sessaoUsuario;
          return res.send(200);
        } else {
          return res.send(500, {
            err: "Senha não corresponde."
          });
        }
      }), function(erro) {
        return res.send(500, {
          err: erro
        });
      });
    },
    requestValidate: function(req) {
      if (!req.session.user) {
        return false;
      }
      if (crypt.gerarSessionToken(req) === req.session.user.token) {
        return true;
      }
    }
  };

}).call(this);
