// Generated by CoffeeScript 1.4.0
(function() {
  var crypt, responseHelper, sys, usuarioModel;

  sys = require("sys");

  usuarioModel = require("./../usuario/usuarioModel");

  crypt = require("./../seguranca/criptografia");

  responseHelper = require("./../helpers/response");

  module.exports = {
    login: function(req, res) {
      var email, senha;
      email = req.body.email;
      senha = req.body.senha;
      return usuarioModel.findByEmail(email, (function(usuario) {
        var sessaoUsuario;
        if (!usuario) {
          console.log("Usuário não encontrado.");
          return responseHelper.sendError(res, "Usuário não encontrado.");
        } else if (usuario.passValidate(senha)) {
          sessaoUsuario = {
            sID: req.sessionID,
            userID: usuario.id,
            userName: usuario.nome,
            userMail: usuario.email,
            token: crypt.gerarSessionToken(req)
          };
          req.session.user = sessaoUsuario;
          console.log("Autenticado.");
          return res.send(200);
        } else {
          console.log("Senha não corresponde.");
          return responseHelper.sendError(res, "Senha não corresponde.");
        }
      }), function(erro) {
        console.log(erro);
        return responseHelper.sendError(res, erro);
      });
    },
    requestValidate: function(req) {
      sys.puts(sys.inspect(req.session.user));
      if (!req.session.user) {
        return false;
      }
      return crypt.gerarSessionToken(req) === req.session.user.token;
    },
    logout: function(req, res) {
      console.log("Entrou no logout");
      if (!this.requestValidate(req)) {
        return;
      }
      sys.puts(sys.inspect(req.session.user));
      delete req.session.user;
      sys.puts(sys.inspect(req.session.user));
      console.log("Realizou logout");
      return res.send(200);
    }
  };

}).call(this);
