// Generated by CoffeeScript 1.4.0
(function() {
  var crypt, messageHelper, responseHelper, sys, usuarioModel;

  sys = require("sys");

  usuarioModel = require("./../usuario/usuarioModel");

  crypt = require("./../security/cryptography");

  responseHelper = require("./../helpers/response");

  messageHelper = require("./../helpers/message");

  module.exports = {
    login: function(req, res) {
      var email, senha;
      email = req.body.email;
      senha = req.body.senha;
      return usuarioModel.findByEmail(email, (function(usuario) {
        var sessaoUsuario;
        if (!usuario) {
          return responseHelper.sendError(res, messageHelper.loginFail);
        } else if (usuario.passValidate(senha)) {
          sessaoUsuario = {
            sID: req.sessionID,
            userID: usuario.id,
            userName: usuario.nome,
            userMail: usuario.email,
            token: crypt.sessionTokenGenerate(req)
          };
          req.session.user = sessaoUsuario;
          return res.send(200);
        } else {
          return responseHelper.sendError(res, messageHelper.loginFail);
        }
      }), function(erro) {
        return responseHelper.sendError(res, erro);
      });
    },
    requestValidate: function(req) {
      if (!req.session.user) {
        return false;
      }
      return crypt.sessionTokenGenerate(req) === req.session.user.token;
    },
    logout: function(req, res) {
      if (!this.requestValidate(req)) {
        return;
      }
      delete req.session.user;
      return res.send(200);
    }
  };

}).call(this);
