// Generated by CoffeeScript 1.4.0
(function() {
  var UsuarioModel, login, sys;

  UsuarioModel = require('./usuarioModel');

  sys = require('sys');

  login = require('./../login/login');

  module.exports = function(app) {
    app.post('/usuario', function(req, res) {
      var usuarioModel;
      if (req.body.senha !== req.body.confirmacaoSenha) {
        res.send(412, {
          errors: {
            confirmacaoSenha: {
              message: 'Confirmação de senha incorreta.',
              path: 'confirmacaoSenha'
            }
          }
        });
        return;
      }
      usuarioModel = new UsuarioModel(req.body);
      return usuarioModel.save(function(e, o) {
        if (e) {
          return res.send(412, e);
        } else {
          return res.send(o);
        }
      });
    });
    app.get('/usuarios', function(req, res) {
      return UsuarioModel.find({}, function(e, o) {
        if (e) {
          return res.send(412, e);
        } else {
          return res.send(o);
        }
      });
    });
    app.get('/usuario/:id', function(req, res) {
      return UsuarioModel.findById(req.params.id, function(e, o) {
        if (e) {
          return res.send(412, e);
        } else {
          return res.send(o);
        }
      });
    });
    app.put('/usuario/:id', function(req, res) {
      return UsuarioModel.findById(req.params.id, function(e, o) {
        if (e) {
          return res.send(412, e);
        } else {
          o.nome = req.body.nome;
          o.email = req.body.email;
          o.senha = req.body.senha;
          return o.save(function(e, o) {
            if (e) {
              return res.send(412, e);
            } else {
              return res.send(o);
            }
          });
        }
      });
    });
    return app["delete"]('/usuario/:id', function(req, res) {
      return UsuarioModel.findById(req.params.id, function(e, o) {
        if (e) {
          return res.send(412, e);
        } else {
          return o.remove(function(e, o) {
            if (e) {
              return res.send(412, e);
            } else {
              return res.send(o);
            }
          });
        }
      });
    });
  };

}).call(this);
