// Generated by CoffeeScript 1.4.0
(function() {
  var crypt;

  crypt = require("./cryptography");

  module.exports = {
    requestValidate: function(req) {
      if (!req.session.user) {
        return false;
      }
      return crypt.sessionTokenGenerate(req) === req.session.user.token;
    }
  };

}).call(this);
