// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    loginFail: "Usuário ou senha incorretos.",
    requiredField: "O preenchimento do campo é obrigatório."
  };

}).call(this);
