// Generated by CoffeeScript 1.4.0
(function() {
  var sys;

  sys = require("sys");

  module.exports = {
    sendError: function(response, error) {
      return response.send(412, error);
    },
    defaultResponse: function(response, error, object) {
      if (error) {
        return response.send(412, error);
      } else {
        return response.send(object);
      }
    }
  };

}).call(this);
